name: boulliau

channels:
    - astropy

dependencies:
    - python=3.5
    - astropy
    - Cython
    - matplotlib
    - numpy
    - scikit-learn
    - scikit-image
    - photutils
    - sphinx-astropy
    - pip:
       - batman-package
